version: '3.9'

services:
  erp:
    build:
      context: .
      dockerfile: ./Dockerfile
    #restart: always
    container_name: erp_program
    depends_on:
      db-erp:
        condition: service_healthy
    # volumes:
    #   - static:/app/static
    ports:
      - "80:80"
    # develop:
    #   watch:
    #     - path: ./scsem/requerimientos.txt
    #       action: rebuild
    #     - path: ./scsem
    #       target: /app
    #       action: sync
    # volumes: 
      

  db-erp:
    image: mysql:8.1.0
    #restart: always
    container_name: erp_db
    environment:
      MYSQL_DATABASE: erp
      MYSQL_USER: erpuser
      MYSQL_PASSWORD: "Contrasena7654/(%&/"
      MYSQL_ROOT_PASSWORD: admin1234
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 20s
      retries: 3
      start_period: 5s
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db:  
  static:  